CC ?= gcc
CFLAGS ?= -std=c11 -O2 -Wall -Wextra -Werror -pedantic -g
LDFLAGS ?=
INCDIR := include
SRCDIR := src
BINDIR ?= bin
OBJDIR ?= .obj
OBJDIRPIC ?= .objpic

LIBCOMMON := $(BINDIR)/libcommon.a

all: $(LIBCOMMON) $(BINDIR)/detect_wfg $(BINDIR)/detect_matrix $(BINDIR)/ddetect $(BINDIR)/demo_deadlock $(BINDIR)/demo_deadlock3 $(BINDIR)/demo_nocycle $(BINDIR)/libdd.so
     $(BINDIR)/detect_wfg $(BINDIR)/detect_matrix $(BINDIR)/ddetect \
     $(BINDIR)/demo_deadlock $(BINDIR)/demo_deadlock3 \
     $(BINDIR)/libdd.so

# --- dirs ---
$(BINDIR) $(OBJDIR) $(OBJDIR)/common $(OBJDIR)/graph \
$(OBJDIRPIC) $(OBJDIRPIC)/common $(OBJDIRPIC)/graph:
	mkdir -p $@

# --- objects (static) ---
$(OBJDIR)/common/%.o: $(SRCDIR)/common/%.c | $(OBJDIR)/common
	$(CC) $(CFLAGS) -I$(INCDIR) -c $< -o $@

$(OBJDIR)/graph/%.o: $(SRCDIR)/graph/%.c | $(OBJDIR)/graph
	$(CC) $(CFLAGS) -I$(INCDIR) -c $< -o $@

$(LIBCOMMON): $(OBJDIR)/common/util.o $(OBJDIR)/graph/graph.o | $(BINDIR)
	ar rcs $@ $^

# --- apps ---
$(BINDIR)/detect_wfg: $(SRCDIR)/wfg/detect_wfg.c $(LIBCOMMON) | $(BINDIR)
	$(CC) $(CFLAGS) -I$(INCDIR) $< -o $@ $(LIBCOMMON) $(LDFLAGS)

$(BINDIR)/detect_matrix: $(SRCDIR)/matrix/detect_matrix.c | $(BINDIR)
	$(CC) $(CFLAGS) -I$(INCDIR) $< -o $@ $(LDFLAGS)

$(BINDIR)/ddetect: $(SRCDIR)/cli/ddetect.c | $(BINDIR)
	$(CC) $(CFLAGS) -I$(INCDIR) $< -o $@ $(LDFLAGS)

$(BINDIR)/demo_deadlock: $(SRCDIR)/demo/demo_deadlock.c | $(BINDIR)
	$(CC) $(CFLAGS) -pthread -I$(INCDIR) $< -o $@

$(BINDIR)/demo_deadlock3: $(SRCDIR)/demo/demo_deadlock3.c | $(BINDIR)
	$(CC) $(CFLAGS) -pthread -I$(INCDIR) $< -o $@

# --- objects (PIC) ---
$(OBJDIRPIC)/common/%.o: $(SRCDIR)/common/%.c | $(OBJDIRPIC)/common
	$(CC) $(CFLAGS) -fPIC -I$(INCDIR) -c $< -o $@

$(OBJDIRPIC)/graph/%.o: $(SRCDIR)/graph/%.c | $(OBJDIRPIC)/graph
	$(CC) $(CFLAGS) -fPIC -I$(INCDIR) -c $< -o $@

# --- shared runtime ---
$(BINDIR)/libdd.so: $(SRCDIR)/runtime/libdd.c $(OBJDIRPIC)/common/util.o $(OBJDIRPIC)/graph/graph.o | $(BINDIR)
	$(CC) $(CFLAGS) -shared -fPIC -I$(INCDIR) $^ -o $@ -ldl -pthread $(LDFLAGS)

# --- utilities ---
fmt:
	clang-format -i $(shell find $(SRCDIR) -name '*.c' -o -name '*.h' 2>/dev/null || true)

clean:
	rm -rf $(OBJDIR) $(OBJDIRPIC) $(BINDIR) demo_deadlock libdd.so

# ==== Sanitizer builds ====
.PHONY: asan tsan ubsan cleanall

asan:
	$(MAKE) clean
	$(MAKE) \
	  BINDIR=bin-asan OBJDIR=.obj-asan OBJDIRPIC=.objpic-asan \
	  CFLAGS="$(CFLAGS) -O1 -fno-omit-frame-pointer -fsanitize=address" \
	  LDFLAGS="$(LDFLAGS) -fsanitize=address"

tsan:
	$(MAKE) clean
	$(MAKE) \
	  BINDIR=bin-tsan OBJDIR=.obj-tsan OBJDIRPIC=.objpic-tsan \
	  CFLAGS="$(CFLAGS) -O1 -fsanitize=thread" \
	  LDFLAGS="$(LDFLAGS) -fsanitize=thread"

ubsan:
	$(MAKE) clean
	$(MAKE) \
	  BINDIR=bin-ubsan OBJDIR=.obj-ubsan OBJDIRPIC=.objpic-ubsan \
	  CFLAGS="$(CFLAGS) -O1 -fsanitize=undefined -fno-sanitize-recover=undefined" \
	  LDFLAGS="$(LDFLAGS) -fsanitize=undefined"

cleanall: clean
	rm -rf .obj-asan .objpic-asan bin-asan \
	       .obj-tsan .objpic-tsan bin-tsan \
	       .obj-ubsan .objpic-ubsan bin-ubsan

$(BINDIR)/demo_nocycle: $(SRCDIR)/demo/demo_nocycle.c | $(BINDIR)
	$(CC) $(CFLAGS) -pthread -I$(INCDIR) $< -o $@
